name: Build

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v2
    - name: Validate SQF
      run: python3 tools/sqf_validator.py
    - name: Validate Config
      run: python3 tools/config_style_checker.py
    - name: Validate Stringtables
      run: python3 tools/stringtable_validator.py
    - name: Check for BOM
      uses: arma-actions/bom-check@master
    - name: Send Discord notification
      uses: 8398a7/action-slack@v2
      if: failure()
      with:
        status: ${{ job.status }}
        author_name: ${{ github.actor }}
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Build with HEMTT
        uses: arma-actions/hemtt@master
        with:
          command: build --release --ci
      - name: Send Discord notification
        uses: 8398a7/action-slack@v2
        if: failure()
        with:
          status: ${{ job.status }}
          author_name: ${{ github.actor }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
